bycCore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/accounts/login/', permanent=False)),
    path('accounts/', include('mainLogin.urls')),
    path('home/', include('mainHome.urls')),
    path('users/', include('rrhh_personal.urls')),
    path('maq_settings/', include('maq_settings.urls'))
] 



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rrhh_personal/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    #path para crear personal
    path('create_personal/', CreatePersonalView.as_view(), name='create_personal'),
    #path para mostrar la tabla del personal
    path('personal_table/', TablePersonalView.as_view(), name='table_personal'),
    #path para crear personal
    path('personal/<int:pk>/edit_personal', PersonalEditView.as_view(), name='edit_personal'),
    path('personal/<int:pk>/detail_personal', PersonalDetailView.as_view(), name='detail_personal'),
    path('personal/<int:pk>/edit_license', PersonalLicenceEditView.as_view(), name='personalLicenceEditView'),
    path('personal/<int:pk>/edit_certification', PersonalCertificationEditView.as_view(), name='personalCertificationEditView'),
    path('personal/<int:pk>/edit_examen', PersonalExamenEditView.as_view(), name='personalExamenEditView')
]

rrhh_personal/models.py
from django.db import models
from datetime import datetime
import os
from django.core.files.storage import FileSystemStorage

#MODELO PARA RUTAS DE LOS DOCUMENTOS---------------------------------------------------------
def obtener_ruta_documento(instance, filename):
    extension = os.path.splitext(filename)[1]
    # Define la carpeta dependiendo de algún atributo o tipo de documento
    if isinstance(instance, LicenciaPorPersonal):
        nombre_archivo = f"LIC_{instance.personal_id.rut}_{instance.claseLicencia_id.claseLicencia}_{extension}"
        return os.path.join('Licencias', nombre_archivo)
    elif isinstance(instance, Certificacion):
        nombre_archivo = f"CERT_{instance.personal_id.rut}_{instance.tipoCertificacion_id.tipoCertificacion}_{extension}"
        return os.path.join('Certificaciones', nombre_archivo)
    elif isinstance(instance, Examen):
        nombre_archivo = f"EXAM_{instance.personal_id.rut}_{instance.tipoEx_id.tipoExamen}_{extension}"
        return os.path.join('Examenes', nombre_archivo)
    else:
        # Si no es ninguno de los casos anteriores, lo guardamos en la raíz
        return os.path.join('Otros', filename)

#RUTA PARA SOBREESCRIBIR ARCHIVO
class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name, max_length=None):
        # Elimina el archivo si ya existe
        if self.exists(name):
            os.remove(os.path.join(self.location, name))
        return name

class Sexo(models.Model):
    sexo_id = models.AutoField(primary_key=True, null=False, blank=False)
    sexo = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.sexo
    
    class Meta:
        db_table = 'sexo'

class EstadoCivil(models.Model):
    estcivil_id = models.AutoField(primary_key=True, null=False, blank=False)
    estadocivil = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.estadocivil
    
    class Meta:
        db_table = 'estadocivil'

class Region(models.Model):
    region_id = models.AutoField(primary_key=True, null=False, blank=False)
    region = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.region
    
    class Meta:
        db_table = 'region'

class Comuna(models.Model):
    comuna_id = models.AutoField(primary_key=True, null=False, blank=False)
    region_id = models.ForeignKey(Region, on_delete=models.CASCADE, db_column='region_id')
    comuna = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.comuna
    
    class Meta:
        db_table = 'comuna'

class Personal(models.Model):
    personal_id = models.AutoField(primary_key=True, null=False, blank=False)
    sexo_id = models.ForeignKey(Sexo, on_delete=models.CASCADE, db_column='sexo_id', null=True, blank=True)
    estcivil_id = models.ForeignKey(EstadoCivil, on_delete=models.CASCADE, db_column='estcivil_id', null=True, blank=True)
    region_id = models.ForeignKey(Region, on_delete=models.CASCADE, db_column='region_id', null=True, blank=True)
    comuna_id = models.ForeignKey(Comuna, on_delete=models.CASCADE, db_column='comuna_id', null=True, blank=True)
    rut = models.CharField(max_length=8, null=False, blank=False, unique=True)
    dvrut = models.CharField(max_length=1, null=False, blank= False)
    nombre = models.CharField(max_length=100, null=False, blank= False)
    apepat = models.CharField(max_length=50, null=False, blank= False)
    apemat = models.CharField(max_length=50)
    fechanac = models.DateField(null=True, blank=True)
    correo = models.CharField(max_length=100, null=False, blank=False, unique=True)
    direccion = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return self.nombre + " " + self.apepat + " " + self.apemat
    
    class Meta:
        db_table = 'Personal'

    def save(self, *args, **kwargs):

        
        self.rut = self.rut.upper()
        self.dvrut = self.dvrut.upper()
        self.nombre = self.nombre.upper()
        self.apepat = self.apepat.upper()
        self.apemat = self.apemat.upper()
        self.correo = self.correo.upper()
        self.direccion = self.direccion.upper()
        super().save(*args, *kwargs)


class Empresa(models.Model):
    empresa_id = models.AutoField(primary_key=True, null=False, blank=False)
    region_id = models.ForeignKey(Region, on_delete=models.CASCADE, db_column='region_id', null=True, blank=True, verbose_name='Región')
    comuna_id = models.ForeignKey(Comuna, on_delete=models.CASCADE, db_column='comuna_id', null=True, blank=True, verbose_name='Comuna')
    rut = models.CharField(max_length=8, null=False, blank=False, unique=True, db_column='rut', verbose_name='Rut')
    dvRut = models.CharField(max_length=1, blank=False, null=False, db_column='dvRut', verbose_name='Digito Verificador')
    razonSocial = models.CharField(max_length=100, null=False, blank=False, db_column='razonSocial', verbose_name='Razón Social')
    nombreFant = models.CharField(max_length=100, null=True, blank=True, db_column='nombreFant', verbose_name='Nombre de fantasía')
    giro = models.CharField(max_length=150, null=False, blank=False, db_column='giro', verbose_name='Giro')
    direccion = models.CharField(max_length=150, blank=False, null=False, db_column='direccion', verbose_name='Dirección')
    telefono = models.CharField(max_length=11, blank=True, null=True, verbose_name='Teléfono')

    def save(self, *args, **kwargs):
        # Convertir a mayúsculas los campos deseados
        self.rut = self.rut.upper()
        self.dvRut = self.dvRut.upper()
        self.razonSocial = self.razonSocial.upper()
        self.nombreFant = self.nombreFant.upper() if self.nombreFant else None
        self.giro = self.giro.upper()
        self.direccion = self.direccion.upper()
        super().save(*args, **kwargs)  # Llamar al método save original

    def __str__(self):
        return self.razonSocial


class DeptoEmpresa(models.Model):
    depto_id = models.AutoField(primary_key=True, blank=False, null=False)
    depto = models.CharField(max_length=50, db_column='depto', blank=False, null=False)

    def __str__(self):
        return self.depto


class Cargo(models.Model):
    cargo_id = models.AutoField(primary_key=True, blank=False, null=False)
    depto_id = models.ForeignKey(DeptoEmpresa, on_delete=models.CASCADE, db_column='depto_id', blank=False, null=False)
    cargo = models.CharField(max_length=50, db_column='cargo', blank=False, null=False)

    def __str__(self):
        return self.cargo


class InfoLaboral(models.Model):
    infolab_id = models.AutoField(primary_key=True, null=False, blank=False)
    personal_id = models.ForeignKey(Personal, on_delete=models.CASCADE, db_column='personal_id', null=False, blank=False)
    empresa_id = models.ForeignKey(Empresa, on_delete=models.CASCADE, db_column='empresa_id', null=False, blank=False)
    depto_id = models.ForeignKey(DeptoEmpresa, on_delete=models.CASCADE, db_column='depto_id', null=False, blank=False)
    cargo_id = models.ForeignKey(Cargo, on_delete=models.CASCADE, db_column='cargo_id',blank=False, null=False)
    fechacontrata = models.DateField(blank=False, null=False)


class TipoAusentismo(models.Model):
    tipoausen_id = models.AutoField(primary_key=True, null=False, blank=False)
    tipo = models.CharField(max_length=100, null=False, blank=False, db_column='tipo' )

    def __str__(self):
        return self.tipo


class Ausentismo(models.Model):
    ausentismo_id = models.AutoField(primary_key=True, null=False, blank=False)
    tipoausen_id = models.ForeignKey(TipoAusentismo, on_delete=models.CASCADE, db_column='tipoausen_id', null=False, blank=False)
    personal_id = models.ForeignKey(Personal, on_delete=models.CASCADE, db_column='personal_id', null=False, blank=False)
    fechaini = models.DateField(null=False, blank=False)
    fechafin = models.DateField(null=False, blank=False)
    observacion = models.TextField(max_length=250, blank=True, null=True)

    def __str__(self):
        trabajador = f"{self.personal_id.nombre} {self.personal_id.apepat} {self.personal_id.apemat}"
        return f"{self.tipoausen_id} - {trabajador} ({self.fechaini} a {self.fechafin})"


#PROVEEDOR -------------------------------------------------------------------------------------

class Proveedor(models.Model):
    proveedor_id = models.AutoField(primary_key=True, null=False, blank=False)
    region_id = models.ForeignKey(Region, on_delete=models.CASCADE, db_column='region_id', null=False, blank=False)
    comuna_id = models.ForeignKey(Comuna, on_delete=models.CASCADE, db_column='comuna_id', null=False, blank=False)
    rut = models.CharField(max_length=8, null=False, blank=False)
    dvRut = models.CharField(max_length=1, null=False, blank=False)
    razonSocial = models.CharField(max_length=100, null=False, blank=False)
    nombreFant = models.CharField(max_length=100, null=True, blank=True)
    giro = models.CharField(max_length=100, null=False, blank=False)
    direccion = models.CharField(max_length=100, null=False, blank=False)


    def __str__(self):
        return self.razonSocial
    


class TipoClasificacion(models.Model):
    tipoClasi_id = models.AutoField(primary_key=True, null=False, blank=False)
    tipo = models.CharField(max_length=50, unique=True, null=False, blank=False)

    def __str__(self):
        return self.tipo 



class ClasificacionProveedor(models.Model):
    clasifProv_id = models.AutoField(primary_key=True, null=False, blank=False)
    tipoClasi_id = models.ForeignKey(TipoClasificacion, on_delete=models.CASCADE, db_column='tipoClasi_id', null=False, blank=False)
    proveedor_id = models.ForeignKey(Proveedor, on_delete=models.CASCADE, db_column='proveedor_id', null=False, blank=False)


#----------------------------------------------------------------------------------------- 

rrhh_personal/templates/personal/CertificationEdit_personal.html
{% extends 'home/index.html' %}
{% load static %}

{% block content %}

<h2>Formulario de Certificaciones</h2>
<h5>{{ usuario.nombre }} {{ usuario.apepat }} {{ usuario.apemat }}</h3><br>
<a href="{% url 'table_personal' %}">Volver</a>


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        <tr>
            <td><label for="{{ form.proveedor_id.id_for_label }}">{{ form.proveedor_id.label }}</label>{{ form.proveedor_id }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.tipoCertificacion_id.id_for_label }}">{{ form.tipoCertificacion_id.label }}</label>{{ form.tipoCertificacion_id }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.fechaEmision.id_for_label }}">{{ form.fechaEmision.label }}</label>{{ form.fechaEmision }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.fechaVencimiento.id_for_label }}">{{ form.fechaVencimiento.label }}</label>{{ form.fechaVencimiento }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.rutaDoc.id_for_label }}">{{ form.rutaDoc.label }}</label>{{ form.rutaDoc }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.observacion.id_for_label }}">{{ form.observacion.label }}</label>{{ form.observacion }}</td>
        </tr>
    </table>
    <button type="submit">Guardar</button>
</form>

<h2>Certificaciones Vigentes</h2>
<table>
    <thead>
        <tr>
            <th>Certificacion</th>
            <th>Fecha de emision</th>
            <th>Fecha Vencimiento</th>
            <th>Documento adjunto</th>
            <th>Comentario</th>
        </tr>
    </thead>
    <tbody>
        {% if historial_de_certificaciones %}
            {% for certificacion in historial_de_certificaciones %}
            <tr>
                <td>{{ certificacion.tipoCertificacion_id }}</td>
           
           
                <td>{{ certificacion.fechaEmision }}</td>
          
          
                <td>{{ certificacion.fechaVencimiento }}</td>
    
   
                {% if certificacion.rutaDoc %}
                    <td><a href="{{ certificacion.rutaDoc.url }}" target="_blank">Ver documento</a></td>
                {% else %}
                    <td>No disponible</td>
                {% endif %}
        
           
                <td>{{ certificacion.observacion }} </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td>No hay datos disponibles</td>
            </tr>
        {% endif %}
    </tbody>
</table>  
{% endblock %}

rrhh_personal/templates/personal/ExamenEdit_personal.html
{% extends 'home/index.html' %}

{% block title %}Formulario de Examenes{% endblock %}

{% block content %}

{% load static %}

<h2>Formulario de Examenes</h2>
<h5>{{ usuario.nombre }} {{ usuario.apepat }} {{ usuario.apemat }}</h3><br>
<a href="{% url 'table_personal' %}">Volver</a>


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <table>
        <tr>
            <td><label for="{{ form.proveedor_id.id_for_label }}">{{ form.proveedor_id.label }}</label>{{ form.proveedor_id }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.tipoEx_id.id_for_label }}">{{ form.tipoEx_id.label }}</label>{{ form.tipoEx_id }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.resultadoEx_id.id_for_label }}">{{ form.resultadoEx_id.label }}</label>{{ form.resultadoEx_id }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.fechaEmision.id_for_label }}">{{ form.fechaEmision.label }}</label>{{ form.fechaEmision }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.fechaVencimiento.id_for_label }}">{{ form.fechaVencimiento.label }}</label>{{ form.fechaVencimiento }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.rutaDoc.id_for_label }}">{{ form.rutaDoc.label }}</label>{{ form.rutaDoc }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.observacion.id_for_label }}">{{ form.observacion.label }}</label>{{ form.observacion }}</td>
        </tr>
    </table>
    <button type="submit">Guardar</button>
</form>

<h2>Examenes Vigentes</h2>
<table>
    <thead>
        <tr>
            <th>Examen</th>
            <th>Proveedor</th>
            <th>Fecha de emision</th>
            <th>Fecha Vencimiento</th>
            <th>Documento adjunto</th>
            <th>Comentario</th>
        </tr>
    </thead>
    <tbody>
        {% if historial_de_examen %}
            {% for examen in historial_de_examen %}
            <tr>
                <td>{{ examen.tipoEx_id }}</td>


                <td>{{ examen.proveedor_id }}</td>
           
        
                <td>{{ examen.fechaEmision }}</td>
          
          
                <td>{{ examen.fechaVencimiento }}</td>
    
   
                {% if examen.rutaDoc %}
                    <td><a href="{{ examen.rutaDoc.url }}" target="_blank">Ver documento</a></td>
                {% else %}
                    <td>No disponible</td>
                {% endif %}
        
           
                <td>{{ examen.observacion }} </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td>No hay datos disponibles</td>
            </tr>
        {% endif %}
    </tbody>
</table>  
{% endblock %}

rrhh_personal/templates/personal/LicenceEdit_personal.html
{% extends 'home/index.html' %}
{% load static %}

{% block content %}

<h2>Formulario de Licencia</h2>
<h5>{{ usuario.nombre }} {{ usuario.apepat }} {{ usuario.apemat }}</h3><br>
<a href="{% url 'table_personal' %}">Volver</a>


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        <tr>
            <td><label for="{{ form.tipoLicencia_id.id_for_label }}">{{ form.tipoLicencia_id.label }}</label>{{ form.tipoLicencia_id }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.claseLicencia_id.id_for_label }}">{{ form.claseLicencia_id.label }}</label>{{ form.claseLicencia_id }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.fechaEmision.id_for_label }}">{{ form.fechaEmision.label }}</label>{{ form.fechaEmision }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.fechaVencimiento.id_for_label }}">{{ form.fechaVencimiento.label }}</label>{{ form.fechaVencimiento }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.rutaDoc.id_for_label }}">{{ form.rutaDoc.label }}</label>{{ form.rutaDoc }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.observacion.id_for_label }}">{{ form.observacion.label }}</label>{{ form.observacion }}</td>
        </tr>
    </table>
    <button type="submit">Guardar</button>
</form>

<h2>Licencias Vigentes</h2>
<table>
    <thead>
        <tr>
            <th>Clase Licencia</th>
            <th>Fecha de emision</th>
            <th>Fecha Vencimiento</th>
            <th>Documento adjunto</th>
            <th>Comentario</th>
        </tr>
    </thead>
    <tbody>
        {% if historial_licencias %}
            {% for licencia in historial_licencias %}
            <tr>
                <td>{{ licencia.claseLicencia_id }}</td>
           
           
                <td>{{ licencia.fechaEmision }}</td>
          
          
                <td>{{ licencia.fechaVencimiento }}</td>
    
   
                {% if licencia.rutaDoc %}
                    <td><a href="{{ licencia.rutaDoc.url }}" target="_blank">Ver documento</a></td>
                {% else %}
                    <td>No disponible</td>
                {% endif %}
        
           
                <td>{{ licencia.observacion }} </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td>No hay datos disponibles</td>
            </tr>
        {% endif %}
    </tbody>
</table>  
{% endblock %}

rrhh_personal/templates/personal/edit_personal.html
{% extends 'home/index.html' %}

{% block title %}Formulario de ingreso de personal{% endblock %}

{% block content %}

{% load static %}



<style>
    input[disabled], select[disabled] {
        background-color: #f0f0f0;  /* Color de fondo gris claro */
        color: #ccc;  /* Color del texto gris */
        cursor: not-allowed;  /* Cambia el cursor a una cruz */
    }
</style>

<h1>Edición de personal</h1>
<div>
    <form method="POST" id="personal-form">
        {% csrf_token %}
        <a href="{% url 'table_personal' %}">Volver</a>
        <table>
            <!-- Campos de Personal -->
            <h3>Información personal</h3>
            <tr>
                <td><label for="{{ form.rut.id_for_label }}">Rut</label></td>
                <td>{{ form.rut }} - {{ form.dvrut }}</td>
            <tr>
                <td><label for="{{ form.nombre.id_for_label }}">Nombre</label></td>
                <td>{{ form.nombre }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.apepat.id_for_label }}">Apellido Paterno</label></td>
                <td>{{ form.apepat }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.apemat.id_for_label }}">Apellido Materno</label></td>
                <td>{{ form.apemat }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.sexo_id.id_for_label }}">Sexo</label></td>
                <td>{{ form.sexo_id }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.fechanac.id_for_label }}">Fecha de nacimiento</label></td>
                <td>{{ form.fechanac }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.estcivil_id.id_for_label }}">Estado civil</label></td>
                <td>{{ form.estcivil_id }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.correo.id_for_label }}">Correo electrónico</label></td>
                <td>{{ form.correo }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.region_id.id_for_label }}">Región</label></td>
                <td>{{ form.region_id }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.comuna_id.id_for_label }}">Comuna</label></td>
                <td>{{ form.comuna_id }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.direccion.id_for_label }}">Dirección</label></td>
                <td>{{ form.direccion }}</td>
            </tr>
        </table>
        <table>     
            <!-- Campos de InfoLaboral -->
            <h3>Información laboral</h3>
            <tr>
                <td><label for="{{ laboral_form.depto_id.id_for_label }}">Departamento</label></td>
                <td>{{ laboral_form.depto_id }}</td>
            </tr>
            <tr>
                <td><label for="{{ laboral_form.cargo_id.id_for_label }}">Cargo</label></td>
                <td>{{ laboral_form.cargo_id }}</td>
            </tr>
            <tr>
                <td><label for="{{ laboral_form.empresa_id.id_for_label }}">Empresa</label></td>
                <td>{{ laboral_form.empresa_id }}</td>
            </tr>
            <tr>
                <td><label for="{{ laboral_form.fechacontrata.id_for_label }}">Fecha de ingreso</label></td>
                <td>{{ laboral_form.fechacontrata }}</td>
            </tr>
        </table>
    
        {% if form.non_field_errors %}
            <div>
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    
        <div>
            <!-- Botón para editar -->
            <button type="button" id="btn_editar">Editar</button>
            <!-- Botón para guardar cambios (oculto inicialmente) -->
            <button type="submit" id="btn_guardar" style="display:none;">Guardar cambios</button>
        </div>
    </form>
    <script src="{% static 'js/edit_personal.js' %}" ></script>

{% endblock %}

rrhh_personal/templates/personal/table_personal.html
{% extends 'home/index.html' %}
{% load static %}
{% block title %}Listado de Personal{% endblock %}

{% block content %}

<!-- Incluye los estilos de DataTables -->
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="{% static 'css/table_personal.css' %}">

<div class="container-fluid">
    <div class="d-flex justify-content-center mt-2 mb-2">
        <h1>Listado de Personal</h1>
    </div>
    <div class="d-flex justify-content-start mb-3">
        <a href="{% url 'create_personal' %}" class="btn btn-ingreso-personal">Ingresar personal</a> 
    </div>
    <!-- Tabla -->
    <div class="table-responsive">
        <table id="personalTable" class="table table-striped table-bordered text-center">
            <!--boton para crear usuario-->
            <thead class="thead-dark">
                <tr>
                    <th>Rut</th>
                    <th>Nombre Completo</th>
                    <th>Departamento</th>
                    <th>Cargo</th>
                    <th>Editar</th>
                    <th>Licencia</th>
                    <th>Certificaciones</th>
                    <th>Exámenes</th>
                </tr>
            </thead>
            <tbody>
                {% for p in personal %}
                <tr>
                    <td>{{ p.rut }}-{{ p.dvrut }}</td>
                    <td>
                        <span>
                            <a href="{% url 'detail_personal' pk=p.personal_id %}" class="view-link">{{ p.nombre }} {{ p.apepat }} {{ p.apemat }}</a>
                        </span>
                    </td>
                    <td>
                        {% if p.infolaboral_set.first %}
                            {{ p.infolaboral_set.first.depto_id.depto }}
                        {% else %}
                            No asignado
                        {% endif %}
                    </td>
                    <td>
                        {% if p.infolaboral_set.first %}
                            {{ p.infolaboral_set.first.cargo_id.cargo }}
                        {% else %}
                            No asignado
                        {% endif %}
                    </td>
                    <td>
                        <span>
                            <a href="{% url 'edit_personal' pk=p.personal_id %}" class="edit-link"><i class="bi bi-pencil-fill"></i></a>
                        </span>
                    </td>
                    <td>
                        <span>
                            <a href="{% url 'personalLicenceEditView' pk=p.personal_id %}" class="edit-link"><i class="bi bi-person-vcard-fill"></i></a>
                        </span>
                    </td>
                    <td>
                        <span>
                            <a href="{% url 'personalCertificationEditView' pk=p.personal_id %}"><i class="bi bi-patch-check-fill"></i></a>
                        </span>
                    </td>
                    <td>
                        <span>
                            <a href="{% url 'personalExamenEditView' pk=p.personal_id %}"><i class="bi bi-clipboard2-pulse-fill"></i></a>
                        </span>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>



<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- JS para DataTables -->
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

<!-- JS para Botones de DataTables -->
<script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>

<!-- JS para exportar PDF (recomendado) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>

<!-- JS para exportar Excel -->
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
<script src="{% static 'js/table_personal.js' %}"></script>

{% endblock %}